Api/221 account coins endpoint
input-output-hk/cardano-rosetta pull request #224
Opened 2020-11-30 05:18 UTC by stuartkuentzel

# Description

Updates the openApi.json spec to 1.4.8.
This moves the `coins` object from `account/balance` to `account/coins`.
In reference to issue #221. The 1.4.8 spec moves the `coins` object from `account/balance` to `account/coins`.
Account Balance Response -> https://www.rosetta-api.org/docs/models/AccountBalanceResponse.html
Account Coins Response -> https://www.rosetta-api.org/docs/models/AccountCoinsResponse.html
Docs for both -> https://www.rosetta-api.org/docs/AccountApi.html#accountbalance

# Proposed Solution

- Update the openApi.json spec to 1.4.8.
- Create new `account/coins` endpoint
- Remove `coins` from `account/balance` endpoint

# Important Changes Introduced
Potentially breaking changes for users of the library, since UTXOs `coins` is moved from `account/balance` to `account/coins`.

# Testing
Adds `account-coins-api.test.ts` to `test/e2e/account`.

2020-11-30 11:42 UTC, AlanVerbner requested changes
Thanks a lot for your PR @stuartkuentzel! it looks really good. I think some test are failing tho.

Also, keep in mind that we are working on `master-next` and we are going to introduce several changes that need to happen before this PR.

2020-11-30 11:43 UTC, AlanVerbner commented on cardano-rosetta-server/src/server/openApi.json
> -              "ttl": { "type": "string" }
please, don't remove our custom fields or `fastify` will not reder them when serializing the response

2020-12-01 02:42 UTC, stuartkuentzel commented
@AlanVerbner thanks for taking a look at it. Sounds like some big code changes will happen before this could get merged, so I'll just close it out for now. Looking forward to the updates.

2020-12-01 02:42 UTC, closed without merging

2020-12-01 17:13 UTC, AlanVerbner commented
Thanksa lot @stuartkuentzel ! I'll try to keep you posted