Fix/construction parse signed transaction fix
input-output-hk/cardano-rosetta pull request #252
Opened 2020-12-16 16:38 UTC by jvieiro

# Description

Adds the bech32 address as a return value in the `/construction/parse` endpoint when stake delegation, stake key deregistration, or withdrawal operations are included.

# References

Closes #250

2020-12-16 16:55 UTC, tomasBustamante approved these changes

2020-12-17 11:07 UTC, AlanVerbner commented on cardano-rosetta-server/src/server/services/cardano-services.ts
> +      const signers = getUniqueAddresses(extraData.map(data => getSignerFromOperation(logger, networkId, data)));
@jvieiro this addresses needed to be unique so I added it.. can you please create a test to validate this statement is working properly please?

2020-12-17 14:04 UTC, jvieiro commented on cardano-rosetta-server/src/server/services/cardano-services.ts
> +      const signers = getUniqueAddresses(extraData.map(data => getSignerFromOperation(logger, networkId, data)));
Added at https://github.com/input-output-hk/cardano-rosetta/pull/252/files#diff-5ed14e66a15e1cf387817c03abbbea2495c0758c58a20bed29e75e9d859e304cR77

2020-12-17 18:25 UTC, AlanVerbner requested changes
Let's not merge this as it might not be the final fix. There is another issue.

2020-12-18 10:44 UTC, AlanVerbner approved these changes

2020-12-18 10:45 UTC, merged