refactor: improved logging and mounts in delegation workflow
input-output-hk/cardano-rosetta pull request #260
Opened 2020-12-29 19:26 UTC by AlanVerbner

# Description

This PR improves delegation workflow to make it easier to use.

# Proposed Solution

1. More logs were added using `print_message`
2. The amount to be received has been reduced to `10 ADA`
3. It properly works if `10 ADA` or more are received in the address

# Important Changes Introduced

n/a

# Testing

As described [here](https://github.com/input-output-hk/cardano-rosetta/tree/master/test/check#delegation-workflow)

2021-01-04 16:10 UTC, james-iohk commented
We can remove line `print_message({"DEBUG!!": {{payment_account_identifier}}});` now

2021-01-04 17:35 UTC, james-iohk requested changes
- We can remove line print_message({"DEBUG!!": {{payment_account_identifier}}}); now
- Consider returning remaining funds to `RECIPIENT` (like transfer workflow does)

2021-01-07 22:08 UTC, AlanVerbner commented
@james-iohk I removed the `DEBUG` message and created an issue (https://github.com/input-output-hk/cardano-rosetta/issues/265) to address the refund

2021-01-11 11:41 UTC, rhyslbw approved these changes

2021-01-11 11:55 UTC, merged