fix: multiassets schema wasn't properly mapped
input-output-hk/cardano-rosetta pull request #280
Opened 2021-01-15 00:38 UTC by AlanVerbner

# Description

After reviewing `serialization-lib` multiassets impl I relized MA mapping wasn't properly done in #278 

# Proposed Solution

- `TransactionOutput` contains, in it's metadata an array of `MultiAssets` (aka token bundle)
- Each `MultiAsset` contains he `policyId` and the list of assets it contains.

# Important Changes Introduced

API changed thi affecting #268 

# Testing

n/a

2021-01-15 05:57 UTC, rhyslbw commented
> TransactionOutput contains, in it's metadata an array of MultiAssets (aka token bundle)

https://github.com/Emurgo/cardano-serialization-lib/pull/108#issuecomment-760664972

2021-01-15 06:14 UTC, rhyslbw requested changes
> TransactionOutput contains, in it's metadata an array of MultiAssets (aka token bundle)

https://github.com/Emurgo/cardano-serialization-lib/pull/108#issuecomment-760664972

I suggest also taking the prose from https://developers.cardano.org/en/development-environments/native-tokens/multi-asset-tokens-explainer/ for our docblocks

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/server/openApi.json
> +      "MultiAssets": {
```suggestion
      "TokenBundle": {
```

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/server/openApi.json
> +        "description": "Multiassets allows to represent Native Tokens",
```suggestion
        "description": "A token bundle is a heterogeneous (‘mixed’) collection of tokens. Any tokens can be bundled together. Token bundles are the standard - and only - way to represent and store assets on the Cardano blockchain.",
```

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/server/openApi.json
> +        "required": ["policy", "assets"],
```suggestion
        "required": ["policyId", "tokens"],
```

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/server/openApi.json
>            "multiassets": {
```suggestion
          "tokenBundles": {
```

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/types/rosetta-types.d.ts
> +    export interface MultiAssets {
```suggestion
    export interface TokenBundle {
```

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/types/rosetta-types.d.ts
> +     * Multiassets allows to represent Native Tokens
```suggestion
     * A token bundle is a heterogeneous (‘mixed’) collection of tokens. Any tokens can be bundled together. Token bundles are the standard - and only - way to represent and store assets on the Cardano blockchain.
```

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/types/rosetta-types.d.ts
> +      policy: string;
```suggestion
      policyId: string;
```

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/types/rosetta-types.d.ts
> +      assets: /* Amount is some Value of a Currency. It is considered invalid to specify a Value without a Currency. */ Amount[];
```suggestion
      tokens: /* Amount is some Value of a Currency. It is considered invalid to specify a Value without a Currency. */ Amount[];
```

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/types/rosetta-types.d.ts
> +      multiassets?: /* Multiassets allows to represent Native Tokens */ MultiAssets[];
```suggestion
      tokenBundles?: /* Heterogeneous collection of tokens. */ TokenBundle[];
```

2021-01-15 06:14 UTC, rhyslbw commented on cardano-rosetta-server/src/server/openApi.json
> +          "assets": {
```suggestion
          "tokens": {
```

2021-01-15 17:51 UTC, guido-ta approved these changes

2021-01-15 19:04 UTC, AlanVerbner commented
I'm mergin this as it's blockign the team. if any changes them can be addressed later.

2021-01-15 19:05 UTC, merged

2021-01-16 02:29 UTC, rhyslbw commented on cardano-rosetta-server/src/types/rosetta-types.d.ts
> +    export interface TokenBundleItem {
This is better named `TokenBundle`. Outputs can have multiple token bundles, so there's no need to append "item"

2021-01-18 13:25 UTC, AlanVerbner commented on cardano-rosetta-server/src/types/rosetta-types.d.ts
> +    export interface TokenBundleItem {
ok, let's do a rename once everything is working (it should be straight forward) but we have several tasks already in progress where the current schema is being used