Feat/269 add ma support for account balance
input-output-hk/cardano-rosetta pull request #283
Opened 2021-01-15 20:47 UTC by jvieiro

# Description

Adds Ma support for `/account/balance`

# References

Resolves #269

2021-01-18 13:39 UTC, AlanVerbner commented on cardano-rosetta-server/src/server/db/blockchain-repository.ts
> +      maName: utxo.maName,
I think you need to do the same parsing at the next file for `maName` as I changed your query, sorry

2021-01-18 13:39 UTC, AlanVerbner commented on cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts
> +  ENCODE(ma_tx_out.name, 'escape') as "maName",
We don't need to do this encoding

2021-01-18 13:40 UTC, AlanVerbner commented on cardano-rosetta-server/src/server/utils/constants.ts
> +export const MULTI_ASSET_DECIMALS = 0;
Multi assets have 0 decimals

2021-01-18 13:42 UTC, AlanVerbner commented on cardano-rosetta-server/src/server/utils/data-mapper.ts
> +export const mapMaAmount = (maUtxo: Utxo): Components.Schemas.Amount => ({
what's the difference between this function and the other one used to map amounts?

2021-01-18 14:03 UTC, AlanVerbner commented on cardano-rosetta-server/test/e2e/account/account-api.test.ts
> +import { latestBlockIdentifier, vpfHashAccountBalances, vpfHashCoins } from '../fixture-data';
what does `vpf` stand for?

2021-01-18 18:16 UTC, jvieiro commented on cardano-rosetta-server/test/e2e/account/account-api.test.ts
> +import { latestBlockIdentifier, vpfHashAccountBalances, vpfHashCoins } from '../fixture-data';
This tries to refer to the address `addr_test1vpfwv0ezc5g8a4mkku8hhy3y3vp92t7s3ul8g778g5yegsgalc6gc`, I changed it to address1vpf everywhere

2021-01-18 18:18 UTC, jvieiro commented on cardano-rosetta-server/src/server/db/blockchain-repository.ts
> +      maName: utxo.maName,
It is being parsed [here](https://github.com/input-output-hk/cardano-rosetta/pull/283/files#diff-0220768f826f063d0956b8a8f05ab18d058268b87a5bc0365d2aa8a362935607R388) using `toString()`.

2021-01-18 18:26 UTC, jvieiro commented on cardano-rosetta-server/src/server/utils/data-mapper.ts
> +export const mapMaAmount = (maUtxo: Utxo): Components.Schemas.Amount => ({
Both receive two different types of data, this also adds a property to the returned obj. I think it can be refactored to be used as a common function.

2021-01-18 18:47 UTC, AlanVerbner commented on cardano-rosetta-server/src/server/utils/data-mapper.ts
> +export const mapMaAmount = (maUtxo: Utxo): Components.Schemas.Amount => ({
ok, let's do it on a separate PR then

2021-01-18 18:47 UTC, AlanVerbner commented on cardano-rosetta-server/test/e2e/account/account-api.test.ts
> +import { latestBlockIdentifier, vpfHashAccountBalances, vpfHashCoins } from '../fixture-data';
LOL ... ok ... now I get it

2021-01-18 19:06 UTC, AlanVerbner approved these changes
lgtm

2021-01-18 19:19 UTC, AlanVerbner commented on cardano-rosetta-server/src/server/utils/data-mapper.ts
> +  utxoDetails.forEach((utxoDetail, index) => {
why not a map or a reduce?

2021-01-18 19:20 UTC, guido-ta reviewed
LGTM 👍

2021-01-18 19:20 UTC, guido-ta commented on cardano-rosetta-server/src/server/utils/data-mapper.ts
> +        const previousValue = (blockBalanceData as BlockUtxos).utxos[index - 1];
I know is not part of the scope of this PR, but it might be good if you consider to add one method to validate `blockBalanceData as BlockUtxos` and avoid casting, i.e:

```
const isBlockUtxos = (block: BlockUtxos | BalanceAtBlock): block is BlockUtxos => {
    return block.hasOwnProperty('utxos');
}
```

Then replace `blockBalanceData.hasOwnProperty('utxos')` with `isBlockUtxos` and remove all casts

2021-01-19 10:14 UTC, AlanVerbner commented on cardano-rosetta-server/test/e2e/fixture-data.ts
> +        }
I'm not sure this is the best way to return this as they are not coin identifiers

2021-01-19 10:14 UTC, AlanVerbner requested changes
Let's discuss about `coin_identifiers` representation

2021-01-20 00:31 UTC, AlanVerbner commented on cardano-rosetta-server/src/server/utils/data-mapper.ts
> +            value: (BigInt(entry.value) + BigInt(current.value)).toString()
https://github.com/input-output-hk/cardano-rosetta/issues/288

2021-01-20 01:18 UTC, AlanVerbner submitted a review, later dismissed

2021-01-20 11:43 UTC, AlanVerbner approved these changes

2021-01-20 11:43 UTC, merged