Rosetta Deployment Tests
input-output-hk/cardano-rosetta pull request #313
Opened 2021-02-03 20:58 UTC by james-iohk

# Description

Adds automated API checks for Rosetta deployments on testnet, stagning, shelley-qa and mary-qa.

# Proposed Solution

Uses Postman to define API test scenarios and uses Newman to execute them via CLI.

# Important Changes Introduced

N/A

# Testing

Run as described in readme.

2021-02-23 16:21 UTC, james-iohk commented on .github/workflows/deployment_test.yml
> +    - feat/deployment-tests
Remove this before merge

2021-02-24 08:40 UTC, rhyslbw requested changes
There are newman run reports committed, is that intentional? Also is there a reason we're not checking `mainnet`?

2021-02-24 08:40 UTC, rhyslbw commented on .github/workflows/deployed_environment-test.yml
> +  push:
Remove the push condition

2021-02-24 08:40 UTC, rhyslbw commented on test/deployed-environment-test/package.json
> +  "description": "### Description Automated API checks for Rosetta deployments on testnet, stagning, shelley-qa and mary-qa.",
```suggestion
  "description": "### Description Automated API checks for Rosetta deployments on testnet, staging, shelley-qa and mary-qa.",
```

2021-02-24 14:54 UTC, james-iohk commented
> There are newman run reports committed, is that intentional? Also is there a reason we're not checking `mainnet`?
1. Woops, nope. Must have slipped in during a final force push.
2. Good shout, I didn't even think we had it deployed there yet.

2021-02-25 08:03 UTC, rhyslbw approved these changes
LGTM. Not sure why the Hydra check failed, as the jobs are showing up as passed.

2021-02-25 08:06 UTC, rhyslbw requested changes
Just picked up a minor typo. Fixing this will also re-run the Hydra jobs to see if we need to escalate to the nix team.

2021-02-25 08:06 UTC, rhyslbw commented on test/deployed-environment-test/README.md
> +Automated API checks for Rosetta deployments on testnet, stagning, shelley-qa and mary-qa. Can also be used for local instance.
```suggestion
Automated API checks for Rosetta deployments on testnet, staging, shelley-qa and mary-qa. Can also be used for local instance.
```

2021-02-25 10:53 UTC, rhyslbw approved these changes

2021-02-25 11:48 UTC, merged