feat: use account identifier instead of address in ConstructionDerive…
input-output-hk/cardano-rosetta pull request #330
Opened 2021-03-30 19:07 UTC by abarretoatix

…Response ConstructionParseResponse SigningPayload

# Description

_A clear and concise description of what this pull request does or fixes._

# Proposed Solution

_**Optional** Explain how does this PR solves the problem stated in [Description](#Description). You can also enumerate different alternatives considered while approaching this task._

# Important Changes Introduced

_**Optional** Notice Reviewers about changes that were introduced while developing this task_

# Testing

_**Optional** Leave some recommendations should be useful while reviewers are testing this PR_

2021-03-30 20:10 UTC, tomasBustamante commented on cardano-rosetta-server/src/server/services/cardano-services.ts
> +};
```suggestion

const addressesToAccountIdentifiers = (addresses: string[]) => addresses.map(address => ({ address }));

const getUniqueAccountIdentifiers = (addresses: string[]) =>
  addressesToAccountIdentifiers(getUniqueAddresses(addresses));
```

2021-04-05 12:31 UTC, jvieiro requested changes

2021-04-05 12:31 UTC, jvieiro commented on cardano-rosetta-server/src/server/openApi.json
> -        "required": ["address"],
This should be replaced by `"required": ["account_identifier"]`

2021-04-05 15:55 UTC, abarretoatix commented on cardano-rosetta-server/src/server/openApi.json
> -        "required": ["address"],
Done

2021-04-06 13:04 UTC, jvieiro approved these changes

2021-04-06 13:04 UTC, merged