feat: changed minFeeA and minFeeB sources. Got them from database
input-output-hk/cardano-rosetta pull request #341
Opened 2021-04-13 19:13 UTC by abarretoatix

# Description

Modified minFeeA and minFeeB sources. Got them from database.

2021-04-27 21:24 UTC, jvieiro requested changes

2021-04-27 21:24 UTC, jvieiro commented on cardano-rosetta-server/src/server/services/network-service.ts
> +let exemptionsFile: Components.Schemas.BalanceExemption[] = [];
```suggestion
const exemptionsFile: Components.Schemas.BalanceExemption[] = (() => {
  let file: Components.Schemas.BalanceExemption[] = [];
  try {
    file = JSON.parse(fs.readFileSync(path.resolve(process.env.EXEMPTION_TYPES_PATH)).toString());
    // eslint-disable-next-line no-empty
  } catch (error) {}
  return file;
})();
```

2021-04-27 21:28 UTC, jvieiro requested changes

2021-04-27 21:28 UTC, jvieiro commented on cardano-rosetta-server/src/server/services/network-service.ts
> +    return getExemptionFile(logger);
With the previous mentioned changes I think it can be reduced to this
```suggestion
    return process.env.EXEMPTION_TYPES_PATH ? exemptionsFile : [];
```

2021-04-28 15:38 UTC, abarretoatix commented on cardano-rosetta-server/src/server/services/network-service.ts
> +    return getExemptionFile(logger);
Changed it as we discussed by slack

2021-04-28 15:38 UTC, abarretoatix commented on cardano-rosetta-server/src/server/services/network-service.ts
> +let exemptionsFile: Components.Schemas.BalanceExemption[] = [];
Changed it as we discussed by slack

2021-04-28 18:36 UTC, merged