feat: adding pool retirement operations
input-output-hk/cardano-rosetta pull request #345
Opened 2021-04-20 18:22 UTC by abarretoatix

2021-04-27 14:16 UTC, jvieiro requested changes
retirement operations should be added to output's related operations at `mapToRosettaTransaction` in `data-mapper`

2021-04-27 14:16 UTC, jvieiro commented on cardano-rosetta-server/src/server/utils/cardano/operations-processor.ts
> +  throw ErrorFactory.missingMetadataParametersForPoolRetirement();
I think this error only applies when the epoch parameter is missing. To validate the address you can use the existing function called `validateAndParsePoolKeyHash` that also parses the value.

2021-04-27 14:26 UTC, jvieiro requested changes

2021-04-27 14:26 UTC, jvieiro commented on cardano-rosetta-server/src/server/utils/cardano/transactions-processor.ts
> +  if (type === OperationType.STAKE_DELEGATION) {
This changes should be reverted

2021-04-27 19:08 UTC, abarretoatix commented on cardano-rosetta-server/src/server/utils/cardano/operations-processor.ts
> +  // eslint-disable-next-line camelcase
Not anymore, removed it

2021-04-29 19:10 UTC, jvieiro requested changes

2021-04-29 19:10 UTC, jvieiro commented on cardano-rosetta-server/src/server/utils/cardano/transactions-processor.ts
> +const parsePoolRetirementToOperations = (
We can delete this function

2021-04-29 19:10 UTC, jvieiro commented on cardano-rosetta-server/src/server/utils/cardano/transactions-processor.ts
> +  const certsCount = certOps.length;
```suggestion
  const certsCount = transactionBody.certs()?.len() || 0;
```

2021-04-30 12:19 UTC, merged