Chore: alonzo-white-1.4 node/db-sync
input-output-hk/cardano-rosetta pull request #403
Opened 2021-08-06 01:33 UTC by jvieiro

# Description

Updates cardano node and db-sync dependencies to alonzo-white-1.4 tag and updates db snapshots in order to support new schema.

2021-08-06 02:54 UTC, rhyslbw requested changes

2021-08-06 02:54 UTC, rhyslbw commented on Dockerfile
> +ARG CARDANO_NODE_VERSION=alonzo-white-1.4
```suggestion
ARG CARDANO_NODE_VERSION=alonzo-purple-1.0
```
The target tag is now `alonzo-purple-1.0`. Config for _alonzo-qa_ network is in https://github.com/input-output-hk/cardano-configurations/commit/ad34c4ef391124d4582e1bf22307950fa299f26b

2021-08-06 02:54 UTC, rhyslbw commented on Dockerfile
> +ARG CARDANO_DB_SYNC_VERSION=alonzo-white-1.4
:+1:

2021-08-06 02:54 UTC, rhyslbw commented on cardano-rosetta-server/docker-compose.yml
> +    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-alonzo-white-1.4}
```suggestion
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-alonzo-purple-1.0}
```

2021-08-06 03:34 UTC, jvieiro commented on Dockerfile
> +ARG CARDANO_NODE_VERSION=alonzo-white-1.4
Is necessary to recreate the snapshots against that tag too?

2021-08-06 11:15 UTC, rhyslbw commented on Dockerfile
> +ARG CARDANO_NODE_VERSION=alonzo-white-1.4
It should be fine for this preliminary version, as the `cardano-db-sync` version has not changed.

2021-08-09 08:17 UTC, rhyslbw requested changes

2021-08-09 08:17 UTC, rhyslbw commented on Dockerfile
> +ARG CARDANO_DB_SYNC_VERSION=alonzo-white-1.4
```suggestion
ARG CARDANO_DB_SYNC_VERSION=alonzo-purple-1.0
```

2021-08-09 08:17 UTC, rhyslbw commented on Dockerfile
> +ARG CARDANO_DB_SYNC_VERSION=alonzo-white-1.4
This tag was recently created to align with the target network. It's pointing to the same commit

2021-08-09 08:17 UTC, rhyslbw commented on cardano-rosetta-server/docker-compose.yml
> +    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-alonzo-white-1.4}
```suggestion
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-alonzo-purple-1.0}
```

2021-08-09 08:25 UTC, rhyslbw commented on Dockerfile
> +ARG CARDANO_NODE_VERSION=alonzo-purple-1.0
```suggestion
ARG CARDANO_NODE_VERSION=alonzo-purple-1.0.1
```

2021-08-09 08:26 UTC, rhyslbw commented on cardano-rosetta-server/docker-compose.yml
> +    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-alonzo-purple-1.0}
```suggestion
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-alonzo-purple-1.0.1}
```

2021-08-09 10:37 UTC, merged