feat: cardano-db-sync snapshot restoration
input-output-hk/cardano-rosetta pull request #442
Opened 2021-11-04 13:20 UTC by rhyslbw

# Description
Users need the ability to utilise the supplied cardano-db-sync snapshots, to expedite the PostgreSQL sync which would otherwise take many hours. As there is no snapshot of the cardano-node state, the restoration should only proceed if the instance contains some state in the expected directory, otherwise cardano-db-sync will roll back to the node’s tip, or genesis in the case of a new instance, and thus eliminate most benefits of the feature. 

# Proposed Solution
Introduces a build argument to download and store the provided remote snapshot
into the image, and then startup logic to restoring unless it's the first run
with no `cardano-node` state.

# Testing
At least 3 scenarios should be tested:

1. Instance fully synced, observe no lengthy sync
2. Instance partially synced, observe a proportional sync
3. New instance, observe snapshot not being applied.

2021-11-05 11:47 UTC, james-iohk commented on README.md
> +#### 1. Apply a Trusted `cardano-db-sync` Snapshot
I think we should bring attention to this sooner than when a user may be required to upgrade because they would have already done an initial full sync. Can add to bottom of Build section.

2021-11-08 12:02 UTC, james-iohk commented
Tested a few scenarios on `testnet`
On feature branch 1807750, built with `$ DOCKER_BUILDKIT=1 docker build  --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NETWORK=testnet     --build-arg SNAPSHOT_URL=https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/11/db-sync-snapshot-schema-11-block-3022711-x86_64.tgz --cache-from=inputoutput/cardano-rosetta:master -t inputoutput/cardano-rosetta:1.5.0-testnet  .`

- Running container with (almost) fully synced node results in db-sync snapshot restoration before services are started, db-sync then proceeds to catch-up with node for the final few blocks.
- Running container with clean volume results in sync from genesis, with log "Skipping snapshot restoration as cardano-node will be syncing from genesis". **But there's a problem. Db-sync doesn't initialise properly, logs:** `postgres@cexplorer FATAL:  database "cexplorer" does not exist`. This causes Rosetta network query to return `"An error occurred for request 2: database \"cexplorer\" does not exist"`
- Running container with node part-synced results in db-sync snapshot restoration, then db-sync waits for node to catchup. Meanwhile, any query to Rosetta will use tip of the snapshot (which won't begin updating until node catches up)
- Stopping and Starting container doesn't re-run snapshot restoration.

2021-11-10 05:09 UTC, rhyslbw commented on README.md
> +#### 1. Apply a Trusted `cardano-db-sync` Snapshot
I'm not sure I follow. I've enhanced the docs in 1529731f131bd222f72c98d5e92e2653f6a2c715, which may change your view on this, so please review and LMK.

2021-11-10 05:09 UTC, rhyslbw commented
> Tested a few scenarios on `testnet` On feature branch [1807750](https://github.com/input-output-hk/cardano-rosetta/commit/1807750ad652d5993b49793c4efc4a419a34b5ef), built with `$ DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NETWORK=testnet --build-arg SNAPSHOT_URL=https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/11/db-sync-snapshot-schema-11-block-3022711-x86_64.tgz --cache-from=inputoutput/cardano-rosetta:master -t inputoutput/cardano-rosetta:1.5.0-testnet .`
> 
> * Running container with (almost) fully synced node results in db-sync snapshot restoration before services are started, db-sync then proceeds to catch-up with node for the final few blocks.
> * Running container with clean volume results in sync from genesis, with log "Skipping snapshot restoration as cardano-node will be syncing from genesis". **But there's a problem. Db-sync doesn't initialise properly, logs:** `postgres@cexplorer FATAL:  database "cexplorer" does not exist`. This causes Rosetta network query to return `"An error occurred for request 2: database \"cexplorer\" does not exist"`
> * Running container with node part-synced results in db-sync snapshot restoration, then db-sync waits for node to catchup. Meanwhile, any query to Rosetta will use tip of the snapshot (which won't begin updating until node catches up)
> * Stopping and Starting container doesn't re-run snapshot restoration.

Fixed in 1529731f131bd222f72c98d5e92e2653f6a2c715

2021-11-11 15:35 UTC, james-iohk reviewed
Confirmed on 1529731 that snapshot restoration is mostly working as desired. Db-sync will always initialise - `cexplorer` error is no longer occurring.

The only issue outstanding is where db-sync snapshot is applied and is then ahead of node state, because db-sync is not rolling back to node state. It instead waits for node to catchup, until then all queries to Rosetta use snapshot tip.
_Then once node catches up db-sync deletes all blocks and starts from 0, at this point it'd be best to run container to apply snapshot again (have reproduced this 2 times)_

2021-12-02 09:31 UTC, rhyslbw commented
The `cardano-db-sync` team has confirmed we're observing the expected behavior @james-iohk. I'll update the documentation to detail the procedure for a fresh install.

2021-12-02 17:59 UTC, james-iohk commented on README.md
> +close to the network tip, before then following the instructions in the [Upgrading section](#upgrading)._
You could refer directly to `#1-apply-a-trusted-cardano-db-sync-snapshot`

2021-12-02 18:03 UTC, james-iohk commented on README.md
> +:information_source: _The snapshot will not be applied if there is no prior `cardano-node` state,
Can we swap this double negative for "The snapshot will only be applied if `cardano-node` is synced past the snapshot point."

This info source overlaps with the one above on line 75, they could be aligned somehow so the info is in one place :thinking:

2021-12-02 18:04 UTC, james-iohk requested changes
Please consider just a couple inline comments about the readme

2021-12-07 03:57 UTC, rhyslbw commented on README.md
> +:information_source: _The snapshot will not be applied if there is no prior `cardano-node` state,
Double negative removed in: https://github.com/input-output-hk/cardano-rosetta/commit/24de937e540cfc668d427fe1dcee3ae00fe3f661

> This info source overlaps with the one above on line 75, they could be aligned somehow so the info is in one place

I considered reducing to a single reference point, but I think it's best to keep as-is given it's better to have the information in context, and it's only a small statement.

2021-12-07 06:22 UTC, james-iohk approved these changes

2021-12-07 08:22 UTC, merged